### ISSUE TITLE
Support for new EC2 instance types

### ISSUE THREAD

**Issue by greenline** [Netflix/asgard#159]
Please add support to Asgard for the new Second generation (M3) Standard instances types (m3.xlarge, m3.2xlarge)

**Comment by nathan-v** [comment]
T2 support would be wonderful.

**Comment by cfieber** [comment]
we are no longer using or maintaining Asgard at Netflix - you could fork and implement this yourself or you could look at Spinnaker, which is the successor (and more) to Asgard and currently supports this feature (http://spinnaker.io)
