### ISSUE TITLE
Add support for new ELB feature: Cross-Zone Load Balancing

### ISSUE THREAD

**Issue by mkrogemann** [Netflix/asgard#416]
Last week, this new interesting feature was made available:

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-disable-crosszone-lb.html

There is currently no way to make use of it in Asgard's API, or is there?

Is this feature in anyone's fork or branch already?

**Comment by nathan-v** [comment]
This would be nice to have.

**Comment by cfieber** [comment]
we are no longer using or maintaining Asgard at Netflix - you could fork and implement this yourself or you could look at Spinnaker, which is the successor (and more) to Asgard and currently supports this feature (http://spinnaker.io)
